### ISSUE TITLE
integrating with itflow

### ISSUE THREAD

**Issue by aftechro** [ssddanbrown/sslcheck#5]
any chance this can be integrated with itflow certificates page?
https://github.com/johnnyq/itflow/blob/master/client_certificates.php

atm, the validity dates have to be inserted manually, but will be nice to get the sslcheck automatically from the domains page
https://github.com/johnnyq/itflow/blob/master/client_domains.php

any chance can you have a look at this please?

Thank you!

**Comment by ssddanbrown** [comment]
Hi @aftechro,

Feel free to use this code in this repo as a basis for implementation to help that project. There's only about 100 lines of code in this, most of which is the command-line output. The SSL work is only a couple of lines. 

I won't be offering an implementation myself since I'm not familiar with ITFlow nor do I have much desire to work on that project to be perfectly honest (Nothing against ITFlow but I have enough projects to distract myself right now). 

As a side note, it's not clear if ITFlow is open-source (Outside of source being accessible), Can't see any license in the repo or site.

Will therefore close this off.

**Comment by aftechro** [comment]
Hey, apologies for delay reply.
Thank you for the permission of trying to implement this :D i`ll give it a try and see how that works.

Thank you!
